apiVersion: v1
kind: Namespace
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  name: tenant-b-prod
  labels:
    istio-injection: enabled
---
apiVersion: v1
kind: ResourceQuota
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  name: compute-quota
  namespace: tenant-b-prod
spec:
  hard:
    requests.cpu: "2"
    requests.memory: 2Gi
    limits.cpu: "4"
    limits.memory: 4Gi
